### ISSUE TITLE
Orientation detection

### ISSUE THREAD

**Issue by DmitriyZhuravlev** [hanlanqian/Vehicle_Orientation_Detect#2]
Great code. Would you like to consider the idea of determining orientation based on the direction of movement?

**Comment by hanlanqian** [comment]
> Great code. Would you like to consider the idea of determining orientation based on the direction of movement?

Yep, It works under the scenario of straight movement while dwarfs when vehicles are turning. So I've eventually chosen the keypoint-detection solution.
